### PR TITLE
basic structure

### PR DESCRIPTION
**Pull request by ilyasbabu**
just a structure

### CODE REVIEW

**Comment by ilyasbabu** [comment]
lets make this together

**Review by Nishkarsh01 — APPROVED** [review]
Great Job!

**Comment by ilyasbabu** [comment]
Can i know in brief what this website is about or could you add that in readme.md

**Comment by Nishkarsh01** [comment]
@ilyasbabu Sure thing, I am adding the description of the website in the readme.md

**Comment by ilyasbabu** [comment]
That would be ideal👍

**Comment by Nishkarsh01** [comment]
I have updated the readme.md and also attached a draw.io flowchart. You may find it useful. There is also a Whatsapp chat group, for more real-time communication.

**Pull request merged**
